from kuda.scrapers.async_scrape import scrape_urls
from kuda.scrapers.highrise.exercise_html_parser import parse_exericse_html
from kuda.scrapers.highrise.workout_html_parser import parse_workout_html
